### ISSUE TITLE
Options for grammer checker: 

### ISSUE THREAD

**Issue by GShotwell** [ropenscilabs/gramr#1]
https://github.com/btford/write-good

I think this could work well for checking RMD text. I guess the user flow would be something like: 
1) In RStudio addin, the user selects which checks they want to use
2) Break RMD text into sentences
3) Pass each sentence through the `writeGood()` function
4) Display the sentence in an editable textbox with the suggestions below,  
5) User makes changes to sentence, then clicks next at which pointed the changed text is stored in an array
6)  After all chunks are checked, replace corrected text in the document

Is that roughly what you were envisioning?

**Comment by jasdumas** [comment]
That is exactly what I was thinking: https://github.com/ropenscilabs/gramr/wiki/Add-in-structure-ideas

**Comment by jasdumas** [comment]
Actually now i'm thinking it may have to be a htmlwidget to avoid the NPM package

**Comment by jasdumas** [comment]
Alright i'm abandoning the htmlwidget and rolling some companion functions!

**Comment by GShotwell** [comment]
Sweet! I'm off for the evening but I'm planning on starting in the morning.
Let me know if you have any thoughts on where I should pick up in the
morning.

**Comment by benmarwick** [comment]
I love the idea of this package! I wrote a little [word count & readability addin](https://github.com/benmarwick/wordcountaddin), and this pkg is a natural companion to that. 

I had a go at bundling write-good into the pkg so there are no external dependencies for this, and I think I've succeeded ([benmarwick/gramr](https://github.com/benmarwick/gramr)). Some notes on how I did that are in [zzz.R](https://github.com/benmarwick/gramr/blob/master/R/zzz.R), mostly following @jeroen's [V8 vignette](https://cran.r-project.org/web/packages/V8/vignettes/npm.html), but with a few variations to make it work.

I've also got the addin working in RStudio, and added some minor functions to  give a little status message when the library is loaded, and a function to run write-good on a file by supplying a filename (for people who don't use RStudio GUI). I've also made a start with some code tests and CI using travis (for linux and OSX, I'm looking [here](https://github.com/sfr/RStudio-Addin-Snippets/blob/master/tests/testthat/test-flip.slash.R) for tests that actually directly test the addin in RStudio). The output still needs some refinement to maximize how informative it is to the user. 

Anyway, hope there's something useful in there for you guys. I'm looking forward to seeing how this pkg develops!

**Comment by jasdumas** [comment]
@benmarwick please submit a pull request and include you name in the authors section of the description! The same for @GShotwell !

**Comment by GShotwell** [comment]
@benmarwick your stuff seems to be a little further along then mine. So why don't we merge in your changes first and then I can add in anything that hasn't been included. 

For the add-in, I was thinking it might be good to have something that would check the text sentence-by-sentence to allow the user to make changes that way. The idea would be to copy how the spell-check function works in RStudio. What do you all think? 

Gordon

**Comment by benmarwick** [comment]
Sure, no worries. My fork has diverged a bit and I have a few merge conflicts to resolve. I'm working on that now and will update you as soon as the PR is made.

**Comment by jasdumas** [comment]
Ahh so i started one ahead of you with just some thoughts on structure and notes! feel free to submit a PR when you are ready :)

**Comment by benmarwick** [comment]
No worries, I'm done for now, your PR should get it all.
