### ISSUE TITLE
Error when executing the write_good_ip() func

### ISSUE THREAD

**Issue by jasdumas** [ropenscilabs/gramr#3]
```r
Error in context_eval(join(src), private$context) : 
  TypeError: Object [object Array] has no method 'substr'
```

This is the Untitled doc that I should be working on and should be picking up the mistakes:

```

so dude This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```

**Comment by benmarwick** [comment]
Something odd with the addin, I think. I also got that error, but only once, then nothing at all. 

What do you get if you run `gramr::write_good_ip()` in the same session? Running from the console works for me:

```
> gramr::write_good_ip()
          index    offset         reason
      1     0           2        "so" adds no meaning
```

**Comment by benmarwick** [comment]
Line breaks seem to be the culprit here. If I change the text to 

```
so dude This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>. When you click click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:
```

then I get

```
> gramr::write_good_ip()
  index offset                              reason
1     0      2                "so" adds no meaning
2   215      5                 "click" is repeated
3   257     12 "be generated" may be passive voice
```

**Comment by jasdumas** [comment]
Oh thats weird behavior - I got the same result as you once I removed the line-break and ran it in the console. I can investigate further. The addins.dcf file references the two different functions in the same file not sure if that could be it 😢

**Comment by benmarwick** [comment]
I think we can add ` untitled_text <- paste0(untitled_text, collapse = " ")` into the fn to combine the input text into a character scalar. That seems to solve the substr error for me.

I think we need to have the addins as `interactive: true` so we can give a msg if there are no problems, not 100% sure about that though

**Comment by benmarwick** [comment]
I think https://github.com/ropenscilabs/gramr/pull/5 will solve this, see how it works for you

**Comment by jasdumas** [comment]
#5 worked well! I close this issue out!

**Comment by benmarwick** [comment]
whew! thanks!
