### ISSUE TITLE
write_good_file not as a Addin?

### ISSUE THREAD

**Issue by jasdumas** [ropenscilabs/gramr#7]
I'm wondering if `write_good_file()` may work better just as a function? Things are getting quirky when loading the addin and there is no **filename** specified initially

```r
> gramr:::write_good_file()
1: "test/testthat/test.Rmd"
2: 
write-good found no problems. Your writing is good!
```

**Comment by benmarwick** [comment]
I agree, I think this fn is most likely to be used in the console or even directly from a terminal. Seems unnecessary to have it on the add-in menu

**Comment by jasdumas** [comment]
Ok, thats reflected in https://github.com/ropenscilabs/gramr/commit/4d1cf047e131a678c8fdb98116c2527e966a1bbe
