### ISSUE TITLE
write-good output

### ISSUE THREAD

**Issue by jasdumas** [ropenscilabs/gramr#8]
A future development task and discussion could be to synthesize the output for readability or in a tidy format so that the changes can be implemented programmatically. The API currently displays the index position along with the reason for output. The CLI displays an output similar to how word processing spell checkers communicate suggestions for editing with the underline. 

```shell

> jasminedumas~/Desktop/GitHub Clone Repos/gramr: write-good --text="It should have been defined there."
In text
=============
It should have been defined there.
               ^^^^^^^^^^^^
"been defined" may be passive voice on line 1 at column 15

```

For example in a tidy format:

| position            | original_sentence                      | reason           |
|---------------------|----------------------------------------|------------------|
| line 1 at column 15 | It should have been defined there. | "been defined" may be passive voice |

**Comment by benmarwick** [comment]
Great idea, I think we can use `knitr::kable` to help with the tidying. Getting the original text snippet to include in the output might be a bit fiddly, let's try it!

**Comment by benmarwick** [comment]
Now #10 will produce output like this

```
| index| offset|reason                              |
|-----:|------:|:-----------------------------------|
|    15|     12|"been defined" may be passive voice |
|    49|      8|"suddenly" can weaken meaning       |
```

But I'm not sure what 'index' and 'offset' are about, and how they refer to the original text. Any thoughts?

**Comment by jasdumas** [comment]
I really like the new output! I thought the index was the column position and the offset was maybe the word length but its not making sense - I may file a issue on the write-good repo and ask
